#!/usr/bin/python

from rpi_greenhouse import GreenhouseIndicator
from time import sleep


def main():
    indicator = GreenhouseIndicator()

    while True:
        indicator.show_status_on_leds()
        sleep(5)


if __name__ == '__main__':
    main()
